server:
  port: 9090
#Forest 全局配置
forest:
  backend: okhttp3             # 后端HTTP框架（默认为 okhttp3）
  max-connections: 1000        # 连接池最大连接数（默认为 500）
  max-route-connections: 500   # 每个路由的最大连接数（默认为 500）
  max-request-queue-size: 100  # [自v1.5.22版本起可用] 最大请求等待队列大小
  max-async-thread-size: 300   # [自v1.5.21版本起可用] 最大异步线程数
  max-async-queue-size: 16     # [自v1.5.22版本起可用] 最大异步线程池队列大小
  timeout: 60000                # [已不推荐使用] 请求超时时间，单位为毫秒（默认为 3000）
  connect-timeout: 60000        # 连接超时时间，单位为毫秒（默认为 timeout）
  read-timeout: 3000           # 数据读取超时时间，单位为毫秒（默认为 timeout）
  max-retry-count: 1           # 请求失败后重试次数（默认为 0 次不重试）
  ssl-protocol: TLS            # 单向验证的HTTPS的默认TLS协议（默认为 TLS）
  log-enabled: true            # 打开或关闭日志（默认为 true）
  log-request: true            # 打开/关闭Forest请求日志（默认为 true）
  log-response-status: true    # 打开/关闭Forest响应状态日志（默认为 true）
  log-response-content: true   # 打开/关闭Forest响应内容日志（默认为 false）

wechat:
  corpId: ww17a41727c5808e2a
  corpSecret: IgSvLlXC7RonN-ogM0PiK_UjQ1PN-ODR6RDf3u8X050
  agentId: 1000002
  notice:
    # 群机器人发送消息
    robot: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=9269444d-f3db-4c2b-a60c-01a1a8569c96
    # 获取access_token
    wechatTokenUrl: https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid={0}&corpsecret={1}
    # 发送应用消息
    sendMsgUrl: https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token={0}
mes:
  baseUrl: https://mesqas.yakimagroup.com:8998
  authUrl: https://mesqas.yakimagroup.com:8998/cloudt/authorization/oauth2/token
  client_id: arch_dev
  client_secret: 123456
  token-ttl: 7200

